// This file was auto-generated by ML.NET Model Builder. 

using FoodObjectDetection;
using Microsoft.ML.Data;


ObjectDetection.Train();
// Create single instance of sample data from first line of dataset for model input.
var image = MLImage.CreateFromFile(@"C:\Users\DENI\source\repos\FireFitBlazor\FoodDetection\bin\Debug\net9.0\012168.jpg");
ObjectDetection.ModelInput sampleData = new ObjectDetection.ModelInput()
{
    Image = image,
};
// Make a single prediction on the sample data and print results.
var predictionResult = ObjectDetection.Predict(sampleData);

var predictedLabel = predictionResult.PredictedLabel;

Console.WriteLine("\n\nPredicted Boxes:\n");
if (predictionResult.PredictedBoundingBoxes == null)
{
    Console.WriteLine("No Predicted Bounding Boxes");
    return;
}
var boxes =
    predictionResult.PredictedBoundingBoxes.Chunk(4)
        .Select(x => new { XTop = x[0], YTop = x[1], XBottom = x[2], YBottom = x[3] })
        .Zip(predictionResult.Score, (a, b) => new { Box = a, Score = b });

foreach (var item in boxes)
{
    Console.WriteLine($"XTop: {item.Box.XTop},YTop: {item.Box.YTop},XBottom: {item.Box.XBottom},YBottom: {item.Box.YBottom}, Score: {item.Score}");
}

